name: Auto GEE Indices

on:
  schedule:
    - cron: '0 2 */14 * *'    # toutes les 2 semaines à 02:00 UTC
  workflow_dispatch:          # permet de lancer manuellement

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installer dépendances
        run: pip install earthengine-api google-auth google-api-python-client paramiko

      - name: Décoder la clé de service base64
        run: echo "${{ secrets.GEE_SA_KEY }}" | base64 -d > sa-key.json

      - name: Lancer l’automatisation
        env:
          SA_KEY_PATH:       sa-key.json
          SFTP_HOST:         ${{ secrets.SFTP_HOST }}
          SFTP_USER:         ${{ secrets.SFTP_USER }}
          SFTP_PASS:         ${{ secrets.SFTP_PASS }}
          SFTP_DEST_FOLDER:  ${{ secrets.SFTP_DEST_FOLDER }}
          SMTP_SERVER:       ${{ secrets.SMTP_SERVER }}
          SMTP_PORT:         ${{ secrets.SMTP_PORT }}
          SMTP_USER:         ${{ secrets.SMTP_USER }}
          SMTP_PASS:         ${{ secrets.SMTP_PASS }}
          ALERT_EMAILS:      ${{ secrets.ALERT_EMAILS }}
          WAIT_TIME:         ${{ secrets.WAIT_TIME }}
        run: python3 script_automate.py